project:
  type: website
  output-dir: docs/

website:
  title: "Laetitia Drago"
  favicon: "Logo_page/favicon.ico"
  page-footer:
    center: "Copyright Â© 2025 Laetitia Drago. All rights reserved."
  navbar:
    logo: "Logo_page/Logo.png"
    title: "Laetitia Drago"
    left:
      - text: Home
        href: index.qmd
      - text: Experience
        href: experience.qmd
      - text: Publications
        href: publications.qmd
      - text: Coding
        href: coding.qmd
      - text: Illustration
        href: illustration.qmd
    right:
      - text: "EN {{< iconify academicons:cv-square >}}"
        href: "documents/CV_Laetitia_Drago_EN.pdf"
        target: _blank
      - text: "FR {{< iconify academicons:cv-square >}}"
        href: "documents/CV_Laetitia_Drago_FR.pdf"
        target: _blank
      - text: "{{< iconify octicon:mark-github-16 >}}"
        href: "https://github.com/dlaetitia"
      - text: "{{< iconify simple-icons:googlescholar >}}"
        href: 'https://scholar.google.com/citations?user=HnReO8UAAAAJ&hl=en&authuser=1'
      - text: "{{< iconify fa6-brands:instagram >}}"
        href: 'https://www.instagram.com/marinelifetales/'
      - text: "{{< iconify fa6-brands:linkedin >}}"
        href: 'https://www.linkedin.com/in/laetitia-drago-926a58188/'



format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    text: |
        <link rel="preload" href="Illustration/Logo/logo.png" as="image">
